### ISSUE TITLE
RELP vs TCP/UDP differences

### ISSUE THREAD

**Issue by sopos** [linux-system-roles/logging#202]
I noticed that there's a different approach to configure RELP vs TCP/UDP even though it is quite similar.
E.g. different port(s) definition, different keys definition. Theoretically, there should be just a different _type_ needed.

Actually I like the way RELP is done.

@nhosoi, I'm just curious why the difference? Is there a technical reason not to keep the same sematic?

**Comment by nhosoi** [comment]
> @nhosoi, I'm just curious why the difference? Is there a technical reason not to keep the same sematic?

@sopos, I do not think there is. But since we already released TCP/UDP in that _old(?)_ style, it'd be harder to change the api. So, I'd like to keep it that way. As you mentioned, REPL is more popular than TCP/UDP. We hope it'd encourage the new customers to go straight to the protocol or the TCP/UDP customers to switch to RELP.

**Comment by nhosoi** [comment]
@sopos, the corresponding TCP/UDP output is forwards ouput that uses omfwd and the corresponding TCP/UDP input is remote input which uses imtcp or imudp - [0]. Could you please tell me some more details about "E.g. different port(s) definition, different keys definition" to understand your requests?

[0]
https://www.rsyslog.com/doc/v8-stable/configuration/modules/omfwd.html
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imtcp.html
https://www.rsyslog.com/doc/v8-stable/configuration/modules/imudp.html
