### ISSUE TITLE
Document supported flows and what logs are collected

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#22]
Please add to documentation the supported flows.

Is this already documented anywhere?

OpenShift logs (viaq, viaq-k8s) - Default output is Viaq elasticsearch. Optional is sending to a second ES and Kibana cluster dedicated to infrastructure logs, by setting openshift_logging_use_ops to true.
Can these logs be sent to remote rsyslog as well at this point?

Rsyslog example - what are the optional outputs at this point?

Default conf - where is data collected to ?

What other outputs are currently supported?

@nhosoi @richm

**Comment by nhosoi** [comment]
> Please add to documentation the supported flows.
> Is this already documented anywhere?

No not yet.  Is it possible to provide some template/format I could follow?  (Sorry, I'm not good at writing a doc...  If there's a template, I think it'd be easier for me not to miss necessary info.)

> OpenShift logs (viaq, viaq-k8s) - Default output is Viaq elasticsearch. Optional is sending to a second ES and Kibana cluster dedicated to infrastructure logs, by setting openshift_logging_use_ops to true.

Correct.  Maybe, I'd drop Kibana since it's one of the client interfaces, which could be replaceble.

> Can these logs be sent to remote rsyslog as well at this point?

At this point, it's not configured.

> Rsyslog example - what are the optional outputs at this point?

This configuration is inherited from debops and pretty much naive, which is "omfile", i.e., written to files in /var/log.

> Default conf - where is data collected to ?

That's the defaut rsyslog.conf from the rsyslog rpm package.

> What other outputs are currently supported?

Not configured yet.   If your question means what outputs rsyslog supports, here's the list.
https://www.rsyslog.com/doc/v8-stable/configuration/modules/idx_output.html

**Comment by jvymazal** [comment]
@sradco for now I am would go with documentation here (in this GitHub repo), for starter a readme.md with some overview, example etc. If you plan on more detailed/elaborate doc, I would do it here as well, with links from readme, when this is accepted upstream (to Ansible Galaxy) the readme is then auto-linked to the role page there.

**Comment by sradco** [comment]
Fixed in #27
