### ISSUE TITLE
[RFE] Add logs handling in case the target Elasticsearch is unavailable

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#38]
Add logs handling in case the target Elasticsearch is unavailable, queuing.

@richm @nhosoi

**Comment by sradco** [comment]
This was closed by mistake.

This is from the example rsyslog configurations:
```
            queue.filename="es-app"
            queue.spoolDirectory=`echo $RSYSLOG_SPOOLDIRECTORY`
            queue.type=`echo $ES_QUEUE_TYPE`
            queue.maxDiskSpace=`echo $ES_QUEUE_MAXDISKSPACE`
            queue.maxFileSize=`echo $ES_QUEUE_MAXFILESIZE`
            queue.checkpointInterval=`echo $ES_QUEUE_CHECKPOINTINTERVAL`
            queue.syncqueuefiles="on"
```
@nhosoi Can you please help with the the defaults for each variable?
What do you set for the different variable in viaq?

**Comment by sradco** [comment]
@richm  @nhosoi  I mean the defaults used by OpenShift.

**Comment by richm** [comment]
The defaults for openshift are set here: https://github.com/openshift/cluster-logging-operator/blob/master/files/rsyslog/rsyslog.sh
For example, the `$RSYSLOG_SPOOLDIRECTORY` is set here https://github.com/openshift/cluster-logging-operator/blob/master/files/rsyslog/rsyslog.sh#L83-L87
```
RSYSLOG_WORKDIRECTORY=${RSYSLOG_WORKDIRECTORY:-/var/lib/rsyslog.pod}
if [ ! -d $RSYSLOG_WORKDIRECTORY ] ; then
    mkdir -p $RSYSLOG_WORKDIRECTORY
fi
RSYSLOG_SPOOLDIRECTORY=${RSYSLOG_SPOOLDIRECTORY:-$RSYSLOG_WORKDIRECTORY}
```
you probably want to use `/var/lib/rsyslog` as the default instead of `/var/lib/rsyslog.pod`
