### ISSUE TITLE
Set omelastocsearch variables for different use cases

### ISSUE THREAD

**Issue by sradco** [linux-system-roles/logging#45]
@richm @nhosoi 

In oVirt we have 2 use cases:
1. logs collected from files
2. metrics collected from collectd using the imtcp rsyslog input plugin.

For logging we would like to retry on failure , but for metrics no.

How should we set the following parameters?
 bulkmode=
 writeoperation=
 bulkid=
 dynbulkid=
 retryfailures=
 retryruleset=

I don't believe we have a message ID ... How do you add message id for logs collected from file?

I think it should be 
bulkmode="on"
 writeoperation="index"
 bulkid=""
 dynbulkid="off"
 retryfailures= for logs -> "on" and for metrics -> "off"
 retryruleset= for logs -> "try_es" and for metrics -> ""

**The issue with "try_es" is that it tries to set $.es_msg_id even if  "bulkid" is "" ....
https://github.com/linux-system-roles/logging/blob/3bc23d034a8deee0ab34eeaae64a6f58cb62e44e/roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml#L105

**Comment by richm** [comment]
On 12/25/18 5:46 AM, Shirly Radco wrote:
> Hi,
>
> In oVirt we have 2 use cases:
> 1. logs collected from files
> 2. metrics collected from collectd using the imtcp rsyslog input plugin.
>
> For logging we would like to retry on failure , but for metrics no.

You will need two separate elasticsearch output then.  I think this is how it works now with fluentd, correct?

Note that fluentd uses tagging to distinguish the source of the messages e.g. https://docs.fluentd.org/v0.12/articles/in_tail#tag-(required)

```
<filter some.**.tag>


```

Rsyslog has a `tag` parameter too - https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html#tag

But rsyslog is more like a general purpose programming language in that you do not have to rely on record tags - you can use anything.  For example, you could use the built in `$inputname` field:

https://www.rsyslog.com/doc/v8-stable/configuration/properties.html#message-properties

```
if $inputname == "imfile" then {

  # record is a log from a log file

} else if $inputname == "imtcp" then {

  # record is a metric from collectd

} else {

  # unknown record

}
```

you could also use $tag instead of input name, or any other field:
```
if $!message startswith "collectd:" then {

  # record is a metric from collectd

}
```

note these are only examples - based on the data, you could do something different

>
> How should we set the following parameters?
>  bulkmode=
>  writeoperation=
>  bulkid=
>  dynbulkid=
>  retryfailures=
>  retryruleset=

For logs, taken from https://github.com/openshift/cluster-logging-operator/blob/master/files/rsyslog/55-elasticsearch.conf:
```
            bulkmode="on"
            writeoperation="create"
            bulkid="id_template"
            dynbulkid="on"
            retryfailures="on"
            retryruleset="try_es"
```

Where `id_template` is defined in https://github.com/openshift/cluster-logging-operator/blob/master/files/rsyslog/20-viaq-templates.conf like this:
```
template(name="id_template" type="string" string="%$.viaq_msg_id%")
```
and $.viaq_msg_id is set in https://github.com/openshift/cluster-logging-operator/blob/master/files/rsyslog/55-elasticsearch.conf:
```
    if strlen($!viaq_msg_id) > 0 then {
        set $.viaq_msg_id = $!viaq_msg_id;
    } else if strlen($.omes!_id) > 0 then {
        # retry
        set $.viaq_msg_id = $.omes!_id;
    } else {
        # NOTE: depends on rsyslog being compiled with --enable-uuid
        set $.viaq_msg_id = $uuid;
    }
```
Note that this code is run in both the retry case and in the first time case.

>
> I dont believe we have a message ID ... How do you add message id for logs collected from file?

Does the collectd data already have a field which is a uuid?  If not, then use the example code above:

In the omelasticsearch action config:
```
            bulkid="id_template"
            dynbulkid="on"
```
This means - construct the message ID dynamically, and use the template `id_template` to generate the value.  The `id_template` does this:
```
template(name="id_template" type="string" string="%$.viaq_msg_id%")
```
which generates the value from the local, non-message variable $.viaq_msg_id

This local, non-message variable is set here: https://github.com/openshift/cluster-logging-operator/blob/master/files/rsyslog/55-elasticsearch.conf#L21

If the record already has a $!viaq_msg_id field, use it

If not, and this is the retry case (it is a retry if strlen($.omes!_id) > 0), then use the $.omes!_id as the value for $.viaq_msg_id

Otherwise, generate a new value for $.viaq_msg_id from the $uuid property (the rsyslog for fedora/rhel/centos is built with --enable-uuid). https://github.com/rsyslog/rsyslog/blob/master/runtime/msg.c#L623

>
>
> I think it should be
> bulkmode="on"
>  writeoperation="index"
>  bulkid=""
>  dynbulkid="off"

see above

>  retryfailures=*for logs *-> "on" and*for metrics* -> "off"

yes

>  retryruleset= *for logs* -> "try_es" and *for metrics* -> ""

Not sure what happens if you have `retryruleset=""` - it would be better to omit the `retryruleset` entirely if not using it

>
>
> ****The issue with "try_es" is that it tries to set $.es_msg_id even if  "bulkid" is "" ....
> https://github.com/linux-system-roles/logging/blob/3bc23d034a8deee0ab34eeaae64a6f58cb62e44e/roles/rsyslog/roles/output_roles/elasticsearch/defaults/main.yaml#L105
>

I think you will always want to use
```
            bulkid="id_template"
            dynbulkid="on"
```
